
Date: 2021-12-31 06:58:07.546310

Program error!

Traceback (most recent call last):
  File "c:\code\bot_swiss\bot_swiss\bot.py", line 781, in <module>
    try: bot.polling(none_stop=True)
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\__init__.py", line 392, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\__init__.py", line 416, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\util.py", line 60, in run
    task(*args, **kwargs)
  File "c:\code\bot_swiss\bot_swiss\bot.py", line 94, in welcome
    if account[account].telegram_id == new_account[0]:
TypeError: string indices must be integers

Date: 2021-12-31 07:00:38.016969

Program error!

Traceback (most recent call last):
  File "c:\code\bot_swiss\bot_swiss\bot.py", line 781, in <module>
    try: bot.polling(none_stop=True)
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\__init__.py", line 392, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\__init__.py", line 416, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\mdpru\AppData\Local\Programs\Python\Python38\lib\site-packages\telebot\util.py", line 60, in run
    task(*args, **kwargs)
  File "c:\code\bot_swiss\bot_swiss\bot.py", line 94, in welcome
    if account[account].telegram_id == new_account[0]:
TypeError: string indices must be integers
